// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ3Y996cfDFOxgCCi8cMMLOhT3LQg8-b8',
    appId: '1:568896988612:web:95a3c0fc72951d4c973091',
    messagingSenderId: '568896988612',
    projectId: 'todo-a2389',
    authDomain: 'todo-a2389.firebaseapp.com',
    databaseURL: 'https://todo-a2389-default-rtdb.firebaseio.com',
    storageBucket: 'todo-a2389.appspot.com',
    measurementId: 'G-VN69J5M1CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNeMUrqBbqWcyxbaxp9QGfCHq98y6LKE0',
    appId: '1:568896988612:android:2fe8f82e29de39b9973091',
    messagingSenderId: '568896988612',
    projectId: 'todo-a2389',
    databaseURL: 'https://todo-a2389-default-rtdb.firebaseio.com',
    storageBucket: 'todo-a2389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHete1KiH48JvQyL4rAfx7T3WDfZpdZSg',
    appId: '1:568896988612:ios:15b1d853f78fad8b973091',
    messagingSenderId: '568896988612',
    projectId: 'todo-a2389',
    databaseURL: 'https://todo-a2389-default-rtdb.firebaseio.com',
    storageBucket: 'todo-a2389.appspot.com',
    iosClientId: '568896988612-peb6h1rnnhh5sb3rnmnom56kn6hbpq8h.apps.googleusercontent.com',
    iosBundleId: 'com.todo.soldier.todoApp',
  );
}
